name: Echo Version

on:
  push:
    branches:
      - production

jobs:
  echo:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - name: echo Version
        run: echo $(cat .version)

      - name: echo current branch
        run: echo $(git branch)